FROM intelonp/centos-source-searchlight-base:2.4.20170321
MAINTAINER Intel Corp. (http://www.intel.com)





COPY extend_start.sh /usr/local/bin/kolla_searchlight_extend_start
RUN chmod 755 /usr/local/bin/kolla_searchlight_extend_start




USER searchlight