FROM intelonp/centos-source-ironic-base:2.3.201610190134
MAINTAINER Intel Corp. (http://www.intel.com)






    
        
    


RUN yum -y install util-linux qemu-img ipmitool parted gdisk psmisc fuse && yum clean all





USER ironic