FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% import "macros.j2" as macros with context %}
{% block ovsdpdk_header %}{% endblock %}

{% block ovsdpdk_install %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
&& /bin/false

{% elif base_distro in ['ubuntu', 'debian'] %}

 {% set ovsdpdk_packages = ['openvswitch-switch-dpdk'] %}

{% endif %}

{{ macros.install_packages(ovsdpdk_packages | customizable("packages")) }}

{% if base_distro in ['ubuntu', 'debian'] %}

RUN update-alternatives --set ovs-vswitchd /usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk

{% endif %}

{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block ovsdpdk_footer %}{% endblock %}
{% block footer %}{% endblock %}
