FROM intelonp/centos-source-base:2.4.20170320
MAINTAINER Intel Corp. (http://www.intel.com)








RUN echo 'source not yet available for centos' \
&& /bin/false









COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start


