FROM intelonp/centos-source-base:2.4.201703130523
MAINTAINER Intel Corp. (http://www.intel.com)



RUN rpm --import http://repos.mesosphere.io/el/RPM-GPG-KEY-mesosphere

RUN rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm

