FROM intelonp/centos-source-trove-base:2.4.20170321
MAINTAINER Intel Corp. (http://www.intel.com)







COPY extend_start.sh /usr/local/bin/kolla_trove_extend_start
RUN chmod 755 /usr/local/bin/kolla_trove_extend_start




USER trove