FROM intelonp/centos-source-ceph-base:2.4.201703130523
MAINTAINER Intel Corp. (http://www.intel.com)






# Clear any customisation by Kolla to entrypoint & command
ENTRYPOINT ["/usr/bin/ceph-fuse"]
CMD []