FROM intelonp/centos-source-ceph-base:17.04.0-test
MAINTAINER Intel Corp. (http://www.intel.com)






# Clear any customisation by Kolla to entrypoint & command
ENTRYPOINT ["/usr/bin/ceph-fuse"]
CMD []