FROM intelonp/centos-source-ovsdpdk:17.04.0
MAINTAINER Intel Corp. (http://www.intel.com)



COPY extend_start.sh /usr/local/bin/kolla_ovsdpdk_extend_start
RUN chmod 755 /usr/local/bin/kolla_ovsdpdk_extend_start


