FROM intelonp/centos-source-senlin-base:2.4.201703130523
MAINTAINER Intel Corp. (http://www.intel.com)





COPY extend_start.sh /usr/local/bin/kolla_senlin_extend_start
RUN chmod 755 /usr/local/bin/kolla_senlin_extend_start




USER senlin