FROM intelonp/centos-source-solum-base:17.04.0
MAINTAINER Intel Corp. (http://www.intel.com)





COPY extend_start.sh /usr/local/bin/kolla_solum_extend_start
RUN chmod 755 /usr/local/bin/kolla_solum_extend_start




USER solum