FROM {{ namespace }}/{{ image_prefix }}ovsdpdk:{{ tag }}
MAINTAINER {{ maintainer }}

{% block ovsdpdk_db_header %}{% endblock %}

COPY ovs_ensure_configured.sh /usr/local/bin/kolla_ensure_ovsdpdk_configured
COPY extend_start.sh /usr/local/bin/kolla_ovsdpdk_extend_start
RUN chmod 755 /usr/local/bin/kolla_ensure_ovsdpdk_configured \
              /usr/local/bin/kolla_ovsdpdk_extend_start

{% block ovsdpdk_db_footer %}{% endblock %}
{% block footer %}{% endblock %}
