FROM intelonp/centos-source-sahara-base:17.04.0-test
MAINTAINER Intel Corp. (http://www.intel.com)







COPY extend_start.sh /usr/local/bin/kolla_sahara_extend_start
RUN chmod 755 /usr/local/bin/kolla_sahara_extend_start




USER sahara