FROM intelonp/centos-source-cloudkitty-base:2.4.201703130523
MAINTAINER Intel Corp. (http://www.intel.com)









COPY extend_start.sh /usr/local/bin/kolla_cloudkitty_extend_start
RUN chmod 755 /usr/local/bin/kolla_cloudkitty_extend_start




USER cloudkitty