FROM intelonp/centos-source-designate-base:2.4.20170321
MAINTAINER Intel Corp. (http://www.intel.com)





# The bind9 package here is only to provide the rndc binary.

    
       
    

RUN yum -y install bind && yum clean all




USER designate