FROM intelonp/centos-source-openvswitch-base:2.3.201610190134
MAINTAINER Intel Corp. (http://www.intel.com)



COPY extend_start.sh /usr/local/bin/kolla_openvswitch_extend_start
RUN chmod 755 /usr/local/bin/kolla_openvswitch_extend_start



